//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_product
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string default_code { get; set; }
        public string name_template { get; set; }
        public Nullable<int> create_uid { get; set; }
        public Nullable<System.DateTime> message_last_post { get; set; }
        public int product_tmpl_id { get; set; }
        public string barcode { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> write_uid { get; set; }
    }
}
